### ISSUE TITLE
v0.9 Roadmap

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis#157]
- Reuse whoosh queries for the papis database
- Use [pybtex](https://pybtex.org/) instead of bibtexparser.
- Fix tests
- Document stevedore plugin system and discuss further where to use it @teto 
  - Is it then possible with stevedore to implement a scihub downloader outside of papis core?
- Document and test the picker infrastructure in `papis.pick`.

**Comment by teto** [comment]
> Reuse whoosh queries for the papis database

what does that imply ? whoosh would always be used ?

> Use pybtex instead of bibtexparser.

why ?

> Is it then possible with stevedore to implement a scihub downloader outside of papis core?

It is definitely possible.

> Document and test the picker infrastructure in papis.pick

I wonder what's the best design there. Forcing a spefic picker interface might be a bad idea. Maybe it's best to make papis more usable as a library ? so that one can build TUIs or even GUIs around it.

**Comment by teto** [comment]
I wonder if you would be open to bump the minimum python to 3.5 and use type hinting. I noticed you add types in the documentation. instead of putting them in the documentation, you could add them directly into the code, thyus allowing static checkers like mypy to be even more effective (and I suppose some documentation generators can extract this information).

**Comment by alejandrogallo** [comment]
It would be nice to have consistent type annotation however I don’t think it’s worth losing compatibility with two versions for that. About static checkers I think before relying on them we should write more tests and think about a more reliable test suite.

**Comment by teto** [comment]
I've started working on plugin support for the `add` command with the added feature that one should not need to specify a format, it would be recognized by the plugins (distinguish between local files vs url vs doi vs isbn etc). Might take some time though (I have only bibtex working).

**Comment by alejandrogallo** [comment]
Hi, this sounds nice, it looks like a great extension to the `--smart` flag now existing in `papis add`

**Comment by alejandrogallo** [comment]
I just implemented stevedore for commands, it's better like that because then we can export directly commands like `papis dmenu` through stevedore, check it out if you'd like.

**Comment by Xunius** [comment]
Hi alejandrogallo,
An utterly shameless comment: I didn't really contribute to papis since tried it out last year, other than posting a couple of bug reports. I thought about writing a GUI for it, but eventually ended up creating a totally different thing (https://github.com/Xunius/MeiTingTrunk). The 1st alpha just came out yesterday and there is quite a lot missing at the moment, including possibly numerous issues. I'm still new in managing a serious python project and the coding style is bit ugly (I'm still not quite used to adding spaces in python commands, and I've written no tests whatsoever before). I wonder whether you could give it a quick look and provide me some suggestions?
Regards

**Comment by teto** [comment]
Looks amazing, kinda hard for me to try it now as I am on the move. 
What stopped you from using papis as a backend ? the API looks nice from what I have seen and it would give you some import/export capabilities right out of the box. 
With the new plugin API, you might even be able to register your own import/exporters.
I would absolutely love to use this as a gui.

**Comment by alejandrogallo** [comment]
Hello @Xunius , it looks amazing and very promising, I'm happy to write you an email as soon as I've taken a look at it. As @teto I'd love to know also why you didn't feel that papis was a suitable fit as the backend of your gui, maybe in the future we can put together an interface for it?

**Comment by Xunius** [comment]
Hi @teto, @alejandrogallo I actually don't know enough of papis's workflow to dislike it, simply because I had some previous experiences with mendeley sqlite structure so I build on my existing code from there. Yes I'd like to try putting them together at some point, that sounds good.

**Comment by alejandrogallo** [comment]
- [X] Reuse whoosh queries for the papis database
- [X] Use pybtex instead of bibtexparser.
  - I thought pybtex is better than bibtexparser because it could also read
  `@string` directives, but I discovered that bibtexparser can also do it, so
  I won't do this.
- [X] Fix tests
- [ ] Document stevedore plugin system and discuss further where to use it
  - Document and test the picker infrastructure in papis.pick.
- [ ] Implement explorer plugin infrastructure for `papis explore`?
  For instance, if we have the package `papis-crossref`, it would implement
  a downloader `from doi` and an explore `papis.crossref.get_data`.
  I have a script for electronics datasheets using `octopart`, then we could
  do `pip install papis-octopart` and it would define a command such like
  ```
  papis explore octopart 'lm318' pick
  ```
  etc.
- [ ] `papis-add` plugin architecture, I don't know if this should go in `v0.9`
  or `v0.10`.

**Comment by teto** [comment]
if I have time after 0.9, I will investigate a fzf picker. I feel an important task would be to clear out any misunderstanding about the different database backend, notably the whoosh one. I am fine with each backedn having it's own search syntax but I think the `--all` flag should work across all backends without an extra query.

**Comment by teto** [comment]
@Xunius if you use the API, you are not bound to papis workflow.
If I look at your README, papis covers most points except:
- Oragnize documents in a folder tree, with arbitrary level of folder nesting.
- Add a document to multiple folders without taking up duplicate storage. (papis can add via symlink but it depends on how you implemented your current mechanism).
- the database is not sqlite but it's possible to add others so it's doable.

As for your TODO list, unsupported are:
- Format citations into various citation styles, in a format suitable to paste into word editors. 
- Full text searching inside PDFs.
but 
 - Import from Zotero and EndNote.
 - Other document types aside articles and books.
are .

About the ideas:
```
    An embedded PDF viewer?
    A PDF preview tab?
    Markdown syntax support in the note tab?
    Custom fields design in the meta data tab?
```
I am for composition of programs/tools so I would vote against all that. Decoupling UI from the backend has various advantages (as Neovim showed) and should allow for more contributors in both projects (since it would impose fewer constraints).

**Comment by ripefig** [comment]
Is automatic bidirectional sync between papis and zotero planned? This could make it possible to create an all-purpose graphical reference client on top of papis (Zotero's interface is terrible).

**Comment by teto** [comment]
what's holding back the v0.9 release ?
